services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=${EMP_DB_NAME}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${EMP_DB_USERNAME}'
      - 'MONGO_INITDB_ROOT_USERNAME=${EMP_DB_PASSWORD}'
    ports:
      - '27017'
